/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import {  Vector3 } from "three";
import AstralBody from "./AstralBody";

export default function Mercury(props) {
  return (
    <AstralBody
      modelPath="/Mercury.glb"
      position={new Vector3(0, 0, 0)}
      scale={0.1}
      cameraPos={[100, 100, 100]}
      {...props}
    />
  );
}
